// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHBdgOXlVzpSJF3X8R3RjpIpWlUgf8OXY',
    appId: '1:249847083388:web:62c5c18d645e1870fdb4f9',
    messagingSenderId: '249847083388',
    projectId: 'myapp-e91fb',
    authDomain: 'myapp-e91fb.firebaseapp.com',
    storageBucket: 'myapp-e91fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqkeNFghHuHxOiF90UulgU8W3UDe_i6ug',
    appId: '1:249847083388:android:ea80aa5414d12d41fdb4f9',
    messagingSenderId: '249847083388',
    projectId: 'myapp-e91fb',
    storageBucket: 'myapp-e91fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFS8vHk5V4Tfau4CMYYa_luaKcJl4QlA',
    appId: '1:249847083388:ios:7569147928411393fdb4f9',
    messagingSenderId: '249847083388',
    projectId: 'myapp-e91fb',
    storageBucket: 'myapp-e91fb.appspot.com',
    androidClientId: '249847083388-edmj583o1l9f0ri7natlar313gofjqcj.apps.googleusercontent.com',
    iosClientId: '249847083388-lrsrkgn1hv38dpqc2agc564ngts3vt4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesManagementMobilleApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpFS8vHk5V4Tfau4CMYYa_luaKcJl4QlA',
    appId: '1:249847083388:ios:7569147928411393fdb4f9',
    messagingSenderId: '249847083388',
    projectId: 'myapp-e91fb',
    storageBucket: 'myapp-e91fb.appspot.com',
    androidClientId: '249847083388-edmj583o1l9f0ri7natlar313gofjqcj.apps.googleusercontent.com',
    iosClientId: '249847083388-lrsrkgn1hv38dpqc2agc564ngts3vt4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesManagementMobilleApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHBdgOXlVzpSJF3X8R3RjpIpWlUgf8OXY',
    appId: '1:249847083388:web:cd006fa990d08ca2fdb4f9',
    messagingSenderId: '249847083388',
    projectId: 'myapp-e91fb',
    authDomain: 'myapp-e91fb.firebaseapp.com',
    storageBucket: 'myapp-e91fb.appspot.com',
  );
}
